version: '3.0'

services:  
  db:
    image: mariadb:11.2
    restart: always
    volumes:
      - type: bind
        source: ./my.cnf
        target: /etc/mysql/my.cnf

    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
    ports:
      - 3307:3307
